{% set name = "astroML" %}
{% set version = "1.0.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45188a7a88a36ca3ec5a3aa04e5fa227f42d17415a6e168fb523375c1aabe291

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy >=1.13
    - scipy >=0.18
    - matplotlib-base >=3
    - scikit-learn >=0.18
    - astropy-base >3

test:
  requires:
    - python {{ python_min }}
  imports:
    - astroML
    - astroML.classification
    - astroML.clustering
    - astroML.datasets
    - astroML.datasets.tools
    - astroML.density_estimation
    - astroML.dimensionality
    - astroML.linear_model
    - astroML.plotting
    - astroML.stats
    - astroML.time_series

about:
  home: http://www.astroML.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for machine learning and data mining in Astronomy
  description: |
    AstroML is a Python module for machine learning and data mining built on
    numpy, scipy, scikit-learn, and matplotlib, and distributed under the BSD
    license. It contains a growing library of statistical and machine learning
    routines for analyzing astronomical data in python, loaders for several
    open astronomical datasets, and a large suite of examples of analyzing and
    visualizing astronomical datasets.
  doc_url: http://www.astroML.org/
  dev_url: https://github.com/astroML/astroML

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - jakevdp
