{% set name = "astroML" %}
{% set version = "0.4.1" %}
{% set hash_type = "sha256" %}
{% set hash_value = "a4efa8acee889c92088ff2433d24793d24cfe7aba15d523e2e0cc12d81e4b899" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.4
    - scipy >=0.11
    - matplotlib-base >=0.99
    - scikit-learn >=0.18
    - astropy >1.2

test:
  imports:
    - astroML
    - astroML.classification
    - astroML.clustering
    - astroML.datasets
    - astroML.datasets.tools
    - astroML.density_estimation
    - astroML.dimensionality
    - astroML.linear_model
    - astroML.plotting
    - astroML.stats
    - astroML.time_series

about:
  home: http://www.astroML.org/
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Tools for machine learning and data mining in Astronomy
  description: |
    AstroML is a Python module for machine learning and data mining built on
    numpy, scipy, scikit-learn, and matplotlib, and distributed under the BSD
    license. It contains a growing library of statistical and machine learning
    routines for analyzing astronomical data in python, loaders for several
    open astronomical datasets, and a large suite of examples of analyzing and
    visualizing astronomical datasets.
  doc_url: http://www.astroML.org/
  dev_url: https://github.com/astroML/astroML

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - jakevdp
