travis:
  secure:
    BINSTAR_TOKEN: g2UinjKIQe0TjxB3y8mkLOcWIF3IcM62u/5XMoQ64i5TCRUDF++DG6iO8bjdJ7KfY+F7F8mWbm+swXs/Ula7Dh3yxzdsGBhp1HkdG1i9G+k6dp/cxVdcmHbn0qAR3yPNMka+D87nvAjZ4jng9t3ZUYocjdYQzz4J1eSNPS6VpN9oVGnbzqyt5ZgHxCwGOUvtf5ByVlovznAplb/c4lA5oAtSIIMxUH6d/oXAQCsFiJg8OvwWVHaIX4lT+x21XKOxtNMKEIUmUHIPYkbLfRQFc6evoEpSRLO3sJ5K82hmM4m55l61qYD1Iq5WkVy7IQkwxP0VFjKGnziuLwtZE9rI+VPtSFvLwFVmyOk1eU6ftaph3OjDNwF3Hcq66vKEZ2J38B5phAWGKaU29MQHpVk+Lv3Bz84juS/WfqkF2wKC386PBrASqr6x8ZxVRfk1PHX8vs7T/c2vvt9eTwp/CZ/nOVfqNO5o2mppHcVhM2HC5+lauxm7sqDyw5hK3NZQy9HFzbIIeHRFhDCGS7MzpiDMulLAlM1zqBhmdIr80VNdjxVX4SIc+/g9rS144Qj4vgoNf1LiVsf60jl1A2NEPOBSouCBoUV0COOeElkMLJ2F5SkDmoFM2cjDKPDao95jA7QhMxdfjAraJQmPX5YkKfO78DQzmO59TfjWpGIWT/JIBWo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
